apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webhook
spec:
  template:
    metadata:
      name: webhook-jvm-latest-latest
  traffic:
    - tag: jvm-latest-latest
      revisionName: webhook-jvm-latest-latest
      percent: 100